export const defaultImages = [
  {
    id: "npGw8vk83WQ",
    slug: "photo-of-clouds-npGw8vk83WQ",
    alternative_slugs: {
      en: "photo-of-clouds-npGw8vk83WQ",
      es: "foto-de-nubes-npGw8vk83WQ",
      ja: "雲の写真-npGw8vk83WQ",
      fr: "photo-de-nuages-npGw8vk83WQ",
      it: "foto-di-nuvole-npGw8vk83WQ",
      ko: "구름-사진-npGw8vk83WQ",
      de: "foto-von-wolken-npGw8vk83WQ",
      pt: "foto-das-nuvens-npGw8vk83WQ",
    },
    created_at: "2017-09-26T16:41:25Z",
    updated_at: "2024-06-03T16:58:30Z",
    promoted_at: "2017-09-28T01:57:41Z",
    width: 4928,
    height: 3264,
    color: "#a6c0c0",
    blur_hash: "LjG+aaxuofj[?^t7j[j[58WCayf6",
    description: "An early drive up Mt. Haleakala for a view of a lifetime.",
    alt_description: "photo of clouds",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1506443973078-d91aa73c0928?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1506443973078-d91aa73c0928?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1506443973078-d91aa73c0928?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1506443973078-d91aa73c0928?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1506443973078-d91aa73c0928?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1506443973078-d91aa73c0928",
    },
    links: {
      self: "https://api.unsplash.com/photos/photo-of-clouds-npGw8vk83WQ",
      html: "https://unsplash.com/photos/photo-of-clouds-npGw8vk83WQ",
      download:
        "https://unsplash.com/photos/npGw8vk83WQ/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
      download_location:
        "https://api.unsplash.com/photos/npGw8vk83WQ/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
    },
    likes: 308,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "4l8ftDYQJAg",
      updated_at: "2023-12-23T12:16:00Z",
      username: "tevintrinh",
      name: "Tevin Trinh",
      first_name: "Tevin",
      last_name: "Trinh",
      twitter_username: "tevintrinh",
      portfolio_url: "http://instagram.com/tevtrinh",
      bio: "capturing dreams",
      location: "Wisconsin",
      links: {
        self: "https://api.unsplash.com/users/tevintrinh",
        html: "https://unsplash.com/@tevintrinh",
        photos: "https://api.unsplash.com/users/tevintrinh/photos",
        likes: "https://api.unsplash.com/users/tevintrinh/likes",
        portfolio: "https://api.unsplash.com/users/tevintrinh/portfolio",
        following: "https://api.unsplash.com/users/tevintrinh/following",
        followers: "https://api.unsplash.com/users/tevintrinh/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1592415874027-25804aa0da70image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1592415874027-25804aa0da70image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1592415874027-25804aa0da70image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "tevtrinh",
      total_collections: 0,
      total_likes: 5,
      total_photos: 153,
      total_promoted_photos: 33,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "tevtrinh",
        portfolio_url: "http://instagram.com/tevtrinh",
        twitter_username: "tevintrinh",
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D5100",
      name: "NIKON CORPORATION, NIKON D5100",
      exposure_time: "1/60",
      aperture: "4.0",
      focal_length: "35.0",
      iso: 100,
    },
    location: {
      name: "Haleakala Peak, United States",
      city: null,
      country: "United States",
      position: {
        latitude: 20.720014,
        longitude: -156.1819636,
      },
    },
    views: 7499487,
    downloads: 8598,
  },
  {
    id: "A--cz3cxstI",
    slug: "man-standing-on-lake-cliff-near-mountain-alps-A--cz3cxstI",
    alternative_slugs: {
      en: "man-standing-on-lake-cliff-near-mountain-alps-A--cz3cxstI",
      es: "hombre-de-pie-en-el-acantilado-del-lago-cerca-de-los-alpes-montanosos-A--cz3cxstI",
      ja: "アルプス山近くの湖の崖の上に立つ男-A--cz3cxstI",
      fr: "homme-debout-sur-la-falaise-du-lac-pres-des-alpes-de-montagne-A--cz3cxstI",
      it: "uomo-in-piedi-sulla-scogliera-del-lago-vicino-alle-alpi-di-montagna-A--cz3cxstI",
      ko: "산-알프스-근처의-호수-절벽에-서-있는-남자-A--cz3cxstI",
      de: "mann-steht-auf-seeklippe-in-der-nahe-von-bergalpen-A--cz3cxstI",
      pt: "homem-em-pe-no-penhasco-do-lago-perto-dos-alpes-da-montanha-A--cz3cxstI",
    },
    created_at: "2016-08-24T02:34:20Z",
    updated_at: "2024-04-01T04:51:06Z",
    promoted_at: "2016-08-24T02:34:20Z",
    width: 4896,
    height: 3264,
    color: "#59738c",
    blur_hash: "LmEMwsWAV?WA_4ofa$bI%Nogj?az",
    description: null,
    alt_description: "man standing on lake cliff near mountain alps",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1472005991841-b135020cad7c?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1472005991841-b135020cad7c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1472005991841-b135020cad7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1472005991841-b135020cad7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1472005991841-b135020cad7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1472005991841-b135020cad7c",
    },
    links: {
      self: "https://api.unsplash.com/photos/man-standing-on-lake-cliff-near-mountain-alps-A--cz3cxstI",
      html: "https://unsplash.com/photos/man-standing-on-lake-cliff-near-mountain-alps-A--cz3cxstI",
      download:
        "https://unsplash.com/photos/A--cz3cxstI/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
      download_location:
        "https://api.unsplash.com/photos/A--cz3cxstI/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
    },
    likes: 613,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "CY5of2Un9a0",
      updated_at: "2023-09-25T06:29:19Z",
      username: "vladshap",
      name: "Vlad Shapochnikov",
      first_name: "Vlad",
      last_name: "Shapochnikov",
      twitter_username: null,
      portfolio_url: "http://vladshap.com",
      bio: null,
      location: null,
      links: {
        self: "https://api.unsplash.com/users/vladshap",
        html: "https://unsplash.com/@vladshap",
        photos: "https://api.unsplash.com/users/vladshap/photos",
        likes: "https://api.unsplash.com/users/vladshap/likes",
        portfolio: "https://api.unsplash.com/users/vladshap/portfolio",
        following: "https://api.unsplash.com/users/vladshap/following",
        followers: "https://api.unsplash.com/users/vladshap/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1470200083100-bb014fe97736?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1470200083100-bb014fe97736?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1470200083100-bb014fe97736?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 0,
      total_photos: 9,
      total_promoted_photos: 3,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: false,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: "http://vladshap.com",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "FUJIFILM",
      model: "X-T1",
      name: "FUJIFILM, X-T1",
      exposure_time: "1/1000",
      aperture: "7.1",
      focal_length: "18.5",
      iso: 200,
    },
    location: {
      name: "Crater Lake, United States",
      city: null,
      country: "United States",
      position: {
        latitude: 42.9445872,
        longitude: -122.1090039,
      },
    },
    views: 7431150,
    downloads: 19394,
  },
  {
    id: "z_Z0ZQVWFSc",
    slug: "brown-and-gray-rock-formation-at-daytime-z_Z0ZQVWFSc",
    alternative_slugs: {
      en: "brown-and-gray-rock-formation-at-daytime-z_Z0ZQVWFSc",
      es: "formacion-rocosa-marron-y-gris-durante-el-dia-z_Z0ZQVWFSc",
      ja: "昼間の茶色と灰色の岩層-z_Z0ZQVWFSc",
      fr: "formation-rocheuse-brune-et-grise-pendant-la-journee-z_Z0ZQVWFSc",
      it: "formazione-rocciosa-marrone-e-grigia-durante-il-giorno-z_Z0ZQVWFSc",
      ko: "낮에는-갈색과-회색-암석이-형성됩니다-z_Z0ZQVWFSc",
      de: "braune-und-graue-felsformation-am-tag-z_Z0ZQVWFSc",
      pt: "formacao-rochosa-marrom-e-cinza-durante-o-dia-z_Z0ZQVWFSc",
    },
    created_at: "2019-10-10T14:27:44Z",
    updated_at: "2024-04-02T02:15:34Z",
    promoted_at: "2019-10-11T07:03:36Z",
    width: 4000,
    height: 6000,
    color: "#738ca6",
    blur_hash: "LVEC?~nhkCofyZNGWBkCE2xuaeRj",
    description: null,
    alt_description: "brown and gray rock formation at daytime",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "feelings",
        title: "Feelings Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cool",
        title: "Cool Images & Photos",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1570717656810-c855a41f35c6?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1570717656810-c855a41f35c6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1570717656810-c855a41f35c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1570717656810-c855a41f35c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1570717656810-c855a41f35c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1570717656810-c855a41f35c6",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-and-gray-rock-formation-at-daytime-z_Z0ZQVWFSc",
      html: "https://unsplash.com/photos/brown-and-gray-rock-formation-at-daytime-z_Z0ZQVWFSc",
      download:
        "https://unsplash.com/photos/z_Z0ZQVWFSc/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
      download_location:
        "https://api.unsplash.com/photos/z_Z0ZQVWFSc/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
    },
    likes: 128,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "AC42mgGybQk",
      updated_at: "2023-09-11T04:44:59Z",
      username: "ryansnell",
      name: "Ryan Snell",
      first_name: "Ryan",
      last_name: "Snell",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: "New Zealand",
      links: {
        self: "https://api.unsplash.com/users/ryansnell",
        html: "https://unsplash.com/@ryansnell",
        photos: "https://api.unsplash.com/users/ryansnell/photos",
        likes: "https://api.unsplash.com/users/ryansnell/likes",
        portfolio: "https://api.unsplash.com/users/ryansnell/portfolio",
        following: "https://api.unsplash.com/users/ryansnell/following",
        followers: "https://api.unsplash.com/users/ryansnell/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1570669256192-9de16ba2c9adimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1570669256192-9de16ba2c9adimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1570669256192-9de16ba2c9adimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "Ryansnellt",
      total_collections: 4,
      total_likes: 0,
      total_photos: 22,
      total_promoted_photos: 4,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "Ryansnellt",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "ILCE-6000",
      name: "SONY, ILCE-6000",
      exposure_time: "1/320",
      aperture: "9.0",
      focal_length: "32.0",
      iso: 100,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 6335434,
    downloads: 4284,
  },
  {
    id: "BgQwFdgSHGQ",
    slug: "a-close-up-of-a-cell-phone-with-a-brown-background-BgQwFdgSHGQ",
    alternative_slugs: {
      en: "a-close-up-of-a-cell-phone-with-a-brown-background-BgQwFdgSHGQ",
      es: "un-primer-plano-de-un-telefono-celular-con-un-fondo-marron-BgQwFdgSHGQ",
      ja: "茶色の背景を持つ携帯電話の接写-BgQwFdgSHGQ",
      fr: "gros-plan-dun-telephone-cellulaire-avec-un-fond-brun-BgQwFdgSHGQ",
      it: "un-primo-piano-di-un-telefono-cellulare-con-uno-sfondo-marrone-BgQwFdgSHGQ",
      ko: "갈색-배경의-휴대폰-클로즈업-BgQwFdgSHGQ",
      de: "eine-nahaufnahme-eines-handys-mit-braunem-hintergrund-BgQwFdgSHGQ",
      pt: "um-close-up-de-um-telefone-celular-com-um-fundo-marrom-BgQwFdgSHGQ",
    },
    created_at: "2023-07-22T17:31:09Z",
    updated_at: "2024-05-28T23:57:43Z",
    promoted_at: "2023-07-26T13:32:01Z",
    width: 4000,
    height: 6000,
    color: "#260c0c",
    blur_hash: "LGF|I]EOSz=v$$=vbHxF9w};WDaz",
    description: null,
    alt_description: "a close up of a cell phone with a brown background",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1690046793216-f66a0f01d5e6?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1690046793216-f66a0f01d5e6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1690046793216-f66a0f01d5e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1690046793216-f66a0f01d5e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1690046793216-f66a0f01d5e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1690046793216-f66a0f01d5e6",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-close-up-of-a-cell-phone-with-a-brown-background-BgQwFdgSHGQ",
      html: "https://unsplash.com/photos/a-close-up-of-a-cell-phone-with-a-brown-background-BgQwFdgSHGQ",
      download:
        "https://unsplash.com/photos/BgQwFdgSHGQ/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
      download_location:
        "https://api.unsplash.com/photos/BgQwFdgSHGQ/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
    },
    likes: 119,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "3d-renders": {
        status: "approved",
        approved_on: "2023-10-17T08:04:45Z",
      },
      wallpapers: {
        status: "rejected",
      },
    },
    asset_type: "photo",
    user: {
      id: "qFQHO9ZSnr4",
      updated_at: "2024-06-03T18:01:43Z",
      username: "martz90",
      name: "Martin Martz",
      first_name: "Martin",
      last_name: "Martz",
      twitter_username: null,
      portfolio_url: null,
      bio: "Photographer, compositing, graphics, mixed media & abstract artist.\r\nAlways grateful for donations to support me: paypal.me/martz90",
      location: "Prague",
      links: {
        self: "https://api.unsplash.com/users/martz90",
        html: "https://unsplash.com/@martz90",
        photos: "https://api.unsplash.com/users/martz90/photos",
        likes: "https://api.unsplash.com/users/martz90/likes",
        portfolio: "https://api.unsplash.com/users/martz90/portfolio",
        following: "https://api.unsplash.com/users/martz90/following",
        followers: "https://api.unsplash.com/users/martz90/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1525547778001-ba86214fbff7?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1525547778001-ba86214fbff7?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1525547778001-ba86214fbff7?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "mtz.artworks",
      total_collections: 0,
      total_likes: 1549,
      total_photos: 316,
      total_promoted_photos: 51,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "mtz.artworks",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: 0,
        longitude: 0,
      },
    },
    views: 2964330,
    downloads: 27844,
  },
  {
    id: "bHbdSmWBTJI",
    slug: "a-mountain-covered-in-snow-with-trees-in-the-foreground-bHbdSmWBTJI",
    alternative_slugs: {
      en: "a-mountain-covered-in-snow-with-trees-in-the-foreground-bHbdSmWBTJI",
      es: "una-montana-cubierta-de-nieve-con-arboles-en-primer-plano-bHbdSmWBTJI",
      ja: "雪に覆われた山と木々-bHbdSmWBTJI",
      fr: "une-montagne-couverte-de-neige-avec-des-arbres-au-premier-plan-bHbdSmWBTJI",
      it: "una-montagna-coperta-di-neve-con-alberi-in-primo-piano-bHbdSmWBTJI",
      ko: "전경에-나무가있는-눈으로-덮인-산-bHbdSmWBTJI",
      de: "ein-schneebedeckter-berg-mit-baumen-im-vordergrund-bHbdSmWBTJI",
      pt: "uma-montanha-coberta-de-neve-com-arvores-em-primeiro-plano-bHbdSmWBTJI",
    },
    created_at: "2022-01-19T18:27:24Z",
    updated_at: "2024-04-09T23:48:36Z",
    promoted_at: "2022-01-20T13:24:01Z",
    width: 4000,
    height: 6000,
    color: "#8c8c8c",
    blur_hash: "LMCZ;FRjWBoy_NfkayaeD%ofWBWV",
    description: "High above Chateau d'Oex",
    alt_description: "a mountain covered in snow with trees in the foreground",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1642616760153-527f6c524083?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1642616760153-527f6c524083?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1642616760153-527f6c524083?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1642616760153-527f6c524083?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1642616760153-527f6c524083?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1642616760153-527f6c524083",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-mountain-covered-in-snow-with-trees-in-the-foreground-bHbdSmWBTJI",
      html: "https://unsplash.com/photos/a-mountain-covered-in-snow-with-trees-in-the-foreground-bHbdSmWBTJI",
      download:
        "https://unsplash.com/photos/bHbdSmWBTJI/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
      download_location:
        "https://api.unsplash.com/photos/bHbdSmWBTJI/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
    },
    likes: 77,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "_jIoYCv8mcs",
      updated_at: "2024-05-08T01:24:17Z",
      username: "larabaeri",
      name: "Lara Baeriswyl",
      first_name: "Lara",
      last_name: "Baeriswyl",
      twitter_username: null,
      portfolio_url: "https://www.lara-baeriswyl.ch",
      bio: "I am a photographer and graphic designer from Switzerland. My heart belongs to the animals, especially my two cats and my horse. I'm available for commissions in Switzerland. I appreciate donations for coffee :-)",
      location: "Switzerland",
      links: {
        self: "https://api.unsplash.com/users/larabaeri",
        html: "https://unsplash.com/@larabaeri",
        photos: "https://api.unsplash.com/users/larabaeri/photos",
        likes: "https://api.unsplash.com/users/larabaeri/likes",
        portfolio: "https://api.unsplash.com/users/larabaeri/portfolio",
        following: "https://api.unsplash.com/users/larabaeri/following",
        followers: "https://api.unsplash.com/users/larabaeri/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1635765494930-5cc198446a83image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1635765494930-5cc198446a83image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1635765494930-5cc198446a83image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "larabaeriswylequine",
      total_collections: 4,
      total_likes: 42,
      total_photos: 163,
      total_promoted_photos: 13,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "larabaeriswylequine",
        portfolio_url: "https://www.lara-baeriswyl.ch",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "ILCE-7",
      name: "SONY, ILCE-7",
      exposure_time: "1/1000",
      aperture: "4.0",
      focal_length: "180.0",
      iso: 160,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 4190940,
    downloads: 26487,
  },
  {
    id: "7hmCn_YE3aU",
    slug: "aerial-view-of-city-buildings-during-night-time-7hmCn_YE3aU",
    alternative_slugs: {
      en: "aerial-view-of-city-buildings-during-night-time-7hmCn_YE3aU",
      es: "vista-aerea-de-los-edificios-de-la-ciudad-durante-la-noche-7hmCn_YE3aU",
      ja: "夜間の都市ビルの空中写真-7hmCn_YE3aU",
      fr: "vue-aerienne-des-batiments-de-la-ville-pendant-la-nuit-7hmCn_YE3aU",
      it: "veduta-aerea-degli-edifici-della-citta-durante-la-notte-7hmCn_YE3aU",
      ko: "야간에-도시-건물의-조감도-7hmCn_YE3aU",
      de: "luftaufnahme-von-stadtgebauden-bei-nacht-7hmCn_YE3aU",
      pt: "vista-aerea-dos-edificios-da-cidade-durante-a-noite-7hmCn_YE3aU",
    },
    created_at: "2018-05-09T04:09:03Z",
    updated_at: "2024-06-03T06:08:43Z",
    promoted_at: "2018-05-09T13:47:26Z",
    width: 4480,
    height: 5600,
    color: "#0c2626",
    blur_hash: "L44oNHs:D$W;MxWBoJoK4may-=ay",
    description: "The skyline of Time Square.",
    alt_description: "aerial view of city buildings during night time",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "feelings",
        title: "Feelings Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cool",
        title: "Cool Images & Photos",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1525838808082-a422ecbce2ff?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1525838808082-a422ecbce2ff?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1525838808082-a422ecbce2ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1525838808082-a422ecbce2ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1525838808082-a422ecbce2ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1525838808082-a422ecbce2ff",
    },
    links: {
      self: "https://api.unsplash.com/photos/aerial-view-of-city-buildings-during-night-time-7hmCn_YE3aU",
      html: "https://unsplash.com/photos/aerial-view-of-city-buildings-during-night-time-7hmCn_YE3aU",
      download:
        "https://unsplash.com/photos/7hmCn_YE3aU/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
      download_location:
        "https://api.unsplash.com/photos/7hmCn_YE3aU/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
    },
    likes: 754,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: "approved",
        approved_on: "2020-04-06T14:20:09Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "YR_kUAmnr18",
      updated_at: "2024-06-03T16:27:54Z",
      username: "trapnation",
      name: "Andre Benz",
      first_name: "Andre",
      last_name: "Benz",
      twitter_username: "benzspeaks",
      portfolio_url: null,
      bio: "Featured in Adobe, Notion, Trello, Figma, Mailchimp.\r\nAvailable for hire worldwide -> andre@nations.io",
      location: "New York, NY.",
      links: {
        self: "https://api.unsplash.com/users/trapnation",
        html: "https://unsplash.com/@trapnation",
        photos: "https://api.unsplash.com/users/trapnation/photos",
        likes: "https://api.unsplash.com/users/trapnation/likes",
        portfolio: "https://api.unsplash.com/users/trapnation/portfolio",
        following: "https://api.unsplash.com/users/trapnation/following",
        followers: "https://api.unsplash.com/users/trapnation/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1513183198594-66e21a4cfe3d?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1513183198594-66e21a4cfe3d?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1513183198594-66e21a4cfe3d?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "benz",
      total_collections: 2,
      total_likes: 91,
      total_photos: 192,
      total_promoted_photos: 139,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "benz",
        portfolio_url: null,
        twitter_username: "benzspeaks",
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 5D Mark IV",
      name: "Canon, EOS 5D Mark IV",
      exposure_time: "1/125",
      aperture: "2.8",
      focal_length: "39.0",
      iso: 3200,
    },
    location: {
      name: "New York, United States",
      city: "New York",
      country: "United States",
      position: {
        latitude: 40.7127753,
        longitude: -74.0059728,
      },
    },
    views: 7383188,
    downloads: 68205,
  },
  {
    id: "RsQycoLyDew",
    slug: "a-view-of-a-mountain-range-with-trees-and-mountains-in-the-background-RsQycoLyDew",
    alternative_slugs: {
      en: "a-view-of-a-mountain-range-with-trees-and-mountains-in-the-background-RsQycoLyDew",
      es: "una-vista-de-una-cadena-montanosa-con-arboles-y-montanas-al-fondo-RsQycoLyDew",
      ja: "木々や山々を背景にした山脈の眺め-RsQycoLyDew",
      fr: "une-vue-dune-chaine-de-montagnes-avec-des-arbres-et-des-montagnes-en-arriere-plan-RsQycoLyDew",
      it: "una-vista-di-una-catena-montuosa-con-alberi-e-montagne-sullo-sfondo-RsQycoLyDew",
      ko: "나무와-산을-배경으로-한-산맥의-모습-RsQycoLyDew",
      de: "blick-auf-eine-bergkette-mit-baumen-und-bergen-im-hintergrund-RsQycoLyDew",
      pt: "uma-vista-de-uma-cordilheira-com-arvores-e-montanhas-ao-fundo-RsQycoLyDew",
    },
    created_at: "2021-09-21T08:43:26Z",
    updated_at: "2024-04-02T05:12:27Z",
    promoted_at: "2021-09-21T13:24:02Z",
    width: 3840,
    height: 2160,
    color: "#404040",
    blur_hash: "LXF=muoIM{oL~qjZRQay?aNHWBoJ",
    description: "Mountain Portrait",
    alt_description:
      "a view of a mountain range with trees and mountains in the background",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1632213702844-1e0615781374?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1632213702844-1e0615781374?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1632213702844-1e0615781374?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1632213702844-1e0615781374?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1632213702844-1e0615781374?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1632213702844-1e0615781374",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-view-of-a-mountain-range-with-trees-and-mountains-in-the-background-RsQycoLyDew",
      html: "https://unsplash.com/photos/a-view-of-a-mountain-range-with-trees-and-mountains-in-the-background-RsQycoLyDew",
      download:
        "https://unsplash.com/photos/RsQycoLyDew/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
      download_location:
        "https://api.unsplash.com/photos/RsQycoLyDew/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
    },
    likes: 211,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "8OiK-ofUmJ4",
      updated_at: "2024-05-22T01:19:46Z",
      username: "ciprian",
      name: "Ciprian Boiciuc",
      first_name: "Ciprian",
      last_name: "Boiciuc",
      twitter_username: "Ciprian_Boiciuc",
      portfolio_url: "http://www.ciprianboiciuc.com",
      bio: "Designer",
      location: "Romania",
      links: {
        self: "https://api.unsplash.com/users/ciprian",
        html: "https://unsplash.com/@ciprian",
        photos: "https://api.unsplash.com/users/ciprian/photos",
        likes: "https://api.unsplash.com/users/ciprian/likes",
        portfolio: "https://api.unsplash.com/users/ciprian/portfolio",
        following: "https://api.unsplash.com/users/ciprian/following",
        followers: "https://api.unsplash.com/users/ciprian/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1498720045703-40b53fd4098e?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1498720045703-40b53fd4098e?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1498720045703-40b53fd4098e?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "ciprian.boiciuc",
      total_collections: 1,
      total_likes: 134,
      total_photos: 109,
      total_promoted_photos: 32,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "ciprian.boiciuc",
        portfolio_url: "http://www.ciprianboiciuc.com",
        twitter_username: "Ciprian_Boiciuc",
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: "Seceda, Santa Cristina Gherdëina, Province of Bolzano - South Tyrol, Italy",
      city: null,
      country: "Italy",
      position: {
        latitude: 46.598057,
        longitude: 11.724168,
      },
    },
    views: 15150987,
    downloads: 53932,
  },
  {
    id: "zst6wWs1m68",
    slug: "black-asphalt-road-near-snow-covered-mountains-during-daytime-zst6wWs1m68",
    alternative_slugs: {
      en: "black-asphalt-road-near-snow-covered-mountains-during-daytime-zst6wWs1m68",
      es: "carretera-de-asfalto-negro-cerca-de-montanas-cubiertas-de-nieve-durante-el-dia-zst6wWs1m68",
      ja: "昼間の雪山付近の黒いアスファルト道路-zst6wWs1m68",
      fr: "route-goudronnee-noire-pres-des-montagnes-enneigees-pendant-la-journee-zst6wWs1m68",
      it: "strada-asfaltata-nera-vicino-a-montagne-innevate-durante-il-giorno-zst6wWs1m68",
      ko: "낮에는-눈-덮인-산-근처의-검은-아스팔트-도로-zst6wWs1m68",
      de: "schwarze-asphaltstrasse-in-der-nahe-von-schneebedeckten-bergen-tagsuber-zst6wWs1m68",
      pt: "estrada-de-asfalto-preto-perto-de-montanhas-cobertas-de-neve-durante-o-dia-zst6wWs1m68",
    },
    created_at: "2021-07-25T11:23:53Z",
    updated_at: "2024-06-03T12:55:42Z",
    promoted_at: "2021-07-25T12:24:02Z",
    width: 3712,
    height: 5568,
    color: "#262626",
    blur_hash: "LZFFHdWBj[oL~WfkazayIVWVj[ay",
    description: null,
    alt_description:
      "black asphalt road near snow covered mountains during daytime",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1627212224531-5241828d0f6d?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1627212224531-5241828d0f6d?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1627212224531-5241828d0f6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1627212224531-5241828d0f6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1627212224531-5241828d0f6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1627212224531-5241828d0f6d",
    },
    links: {
      self: "https://api.unsplash.com/photos/black-asphalt-road-near-snow-covered-mountains-during-daytime-zst6wWs1m68",
      html: "https://unsplash.com/photos/black-asphalt-road-near-snow-covered-mountains-during-daytime-zst6wWs1m68",
      download:
        "https://unsplash.com/photos/zst6wWs1m68/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
      download_location:
        "https://api.unsplash.com/photos/zst6wWs1m68/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
    },
    likes: 514,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2021-08-20T15:50:33Z",
      },
      wallpapers: {
        status: "approved",
        approved_on: "2021-08-20T15:50:30Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "LfkDn6iQykc",
      updated_at: "2024-06-03T19:59:08Z",
      username: "kristapsungurs",
      name: "Kristaps Ungurs",
      first_name: "Kristaps",
      last_name: "Ungurs",
      twitter_username: null,
      portfolio_url: "https://www.instagram.com/kristapsungurs/",
      bio: "Saules mūžu Latvijai\r\n🇱🇻",
      location: "Riga,Latvia",
      links: {
        self: "https://api.unsplash.com/users/kristapsungurs",
        html: "https://unsplash.com/@kristapsungurs",
        photos: "https://api.unsplash.com/users/kristapsungurs/photos",
        likes: "https://api.unsplash.com/users/kristapsungurs/likes",
        portfolio: "https://api.unsplash.com/users/kristapsungurs/portfolio",
        following: "https://api.unsplash.com/users/kristapsungurs/following",
        followers: "https://api.unsplash.com/users/kristapsungurs/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1572640061210-c7b0e4c77d42image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1572640061210-c7b0e4c77d42image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1572640061210-c7b0e4c77d42image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "kristapsungurs",
      total_collections: 17,
      total_likes: 263,
      total_photos: 4149,
      total_promoted_photos: 884,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "kristapsungurs",
        portfolio_url: "https://www.instagram.com/kristapsungurs/",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: "Iceland",
      city: null,
      country: "Iceland",
      position: {
        latitude: 64.963051,
        longitude: -19.020835,
      },
    },
    views: 29976625,
    downloads: 78097,
  },
  {
    id: "d4X8EFP-tRs",
    slug: "top-view-photography-of-sand-d4X8EFP-tRs",
    alternative_slugs: {
      en: "top-view-photography-of-sand-d4X8EFP-tRs",
      es: "vista-superior-fotografia-de-arena-d4X8EFP-tRs",
      ja: "砂の上面写真-d4X8EFP-tRs",
      fr: "photographie-de-vue-de-dessus-du-sable-d4X8EFP-tRs",
      it: "vista-dallalto-fotografia-di-sabbia-d4X8EFP-tRs",
      ko: "모래의-평면도-사진-d4X8EFP-tRs",
      de: "draufsicht-fotografie-von-sand-d4X8EFP-tRs",
      pt: "top-view-fotografia-de-areia-d4X8EFP-tRs",
    },
    created_at: "2018-02-02T12:26:26Z",
    updated_at: "2024-06-03T18:07:20Z",
    promoted_at: "2018-02-02T14:49:14Z",
    width: 6016,
    height: 4016,
    color: "#d9d9f3",
    blur_hash: "LANwWz-oW0%3~ps:offQRsa#RkIo",
    description: "snow desert",
    alt_description: "top view photography of sand",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1517574333057-f91e5dd81126?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1517574333057-f91e5dd81126?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1517574333057-f91e5dd81126?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1517574333057-f91e5dd81126?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1517574333057-f91e5dd81126?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1517574333057-f91e5dd81126",
    },
    links: {
      self: "https://api.unsplash.com/photos/top-view-photography-of-sand-d4X8EFP-tRs",
      html: "https://unsplash.com/photos/top-view-photography-of-sand-d4X8EFP-tRs",
      download:
        "https://unsplash.com/photos/d4X8EFP-tRs/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
      download_location:
        "https://api.unsplash.com/photos/d4X8EFP-tRs/download?ixid=M3w2MTkwMDR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTc0NTI4NTJ8",
    },
    likes: 125,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "MCMtCDmWLOY",
      updated_at: "2024-04-11T12:36:56Z",
      username: "yangshuo",
      name: "Yang",
      first_name: "Yang",
      last_name: null,
      twitter_username: null,
      portfolio_url: "https://yangshuo.tuchong.com",
      bio: "Thank you for your interests.",
      location: "Beijing, China",
      links: {
        self: "https://api.unsplash.com/users/yangshuo",
        html: "https://unsplash.com/@yangshuo",
        photos: "https://api.unsplash.com/users/yangshuo/photos",
        likes: "https://api.unsplash.com/users/yangshuo/likes",
        portfolio: "https://api.unsplash.com/users/yangshuo/portfolio",
        following: "https://api.unsplash.com/users/yangshuo/following",
        followers: "https://api.unsplash.com/users/yangshuo/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1547516215060-2935cbd6f0e3?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1547516215060-2935cbd6f0e3?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1547516215060-2935cbd6f0e3?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 7,
      total_photos: 126,
      total_promoted_photos: 24,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: null,
        portfolio_url: "https://yangshuo.tuchong.com",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D750",
      name: "NIKON CORPORATION, NIKON D750",
      exposure_time: "1/1000",
      aperture: "7.1",
      focal_length: "85.0",
      iso: 50,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 5539188,
    downloads: 4636,
  },
];
